AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sqstasks

  Sample SAM Template for sqstasks

Globals:
  Function:
    Timeout: 60

Resources:
  DefaultQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: "DefaultQueue"

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.6
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get

  ClockFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.clock_handler
      Runtime: python3.6
      Environment:
        Variables:
          QUEUE_URL: !Ref DefaultQueue
      Policies:
        - SQSSendMessagePolicy:
            QueueName:
              !GetAtt DefaultQueue.QueueName
      Events:
        OnTime:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)
            Name: on-time
            Description: Schedule to keep this running on time
            Enabled: true

  WorkerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.sqs_handler
      Runtime: python3.6
      Environment:
        Variables:
          QUEUE_URL: !Ref DefaultQueue
      Policies:
        - SQSSendMessagePolicy:
            QueueName:
              !GetAtt DefaultQueue.QueueName
        - SQSPollerPolicy:
            QueueName:
              !GetAtt DefaultQueue.QueueName
      Events:
        SQSMessage:
          Type: SQS
          Properties:
            Queue:
              !GetAtt DefaultQueue.Arn
            BatchSize: 1
            Enabled: true


Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  QueueURL:
    Description: "URL of new Amazon SQS Queue"
    Value: !Ref "DefaultQueue"
  ClockFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt ClockFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
